CREATE TABLE IF NOT EXISTS people (
    id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS contacts (
    id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    person_id  INT UNSIGNED NOT NULL,
    type       ENUM('phone', 'email', 'whatsapp') NOT NULL,
    value      VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_contacts_person FOREIGN KEY (person_id) REFERENCES people (id) ON DELETE CASCADE,
    INDEX idx_contacts_person_id (person_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
